services:
  spa2mqtt:
    build: .
    container_name: spa2mqtt
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - VARIANT_DEFINITION=${VARIANT_DEFINITION}
      - SPA_IP=${SPA_IP}
      - SPA_PORT=${SPA_PORT}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
